services:
  - type: web
    name: quarkus-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*-runner.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: QUARKUS_HTTP_PORT
        value: 8080
